#!/usr/bin/env bash
# ============================================================================
# moodle-deploy: Deploy Moodle plugins to a local Docker-in-Orb environment
# ============================================================================
# Auto-detects: Orb VM → Docker container → Moodle webroot
# Then copies plugin files and runs upgrade + cache purge.
#
# Usage:
#   bash deploy.sh --source /path/to/plugin/dir [options]
#
# See --help for all options.
# ============================================================================

set -euo pipefail

# ---------- Defaults ----------
SOURCE_DIR=""
ORB_VM=""
CONTAINER=""
WEBROOT=""
DRY_RUN=false
SKIP_UPGRADE=false
SKIP_CACHE=false
PHPUNIT_INIT=false
VERBOSE=false
CONFIG_FILE="$HOME/.moodle-deploy.conf"

# ---------- Colors ----------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ---------- Helpers ----------
info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✓${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; }
step()    { echo -e "\n${BOLD}${CYAN}▸ $*${NC}"; }
debug()   { $VERBOSE && echo -e "  ${CYAN}→${NC} $*" || true; }

die() { error "$*"; exit 1; }

# ---------- Parse arguments ----------
show_help() {
    cat <<'EOF'
Usage: deploy.sh --source <dir> [options]

Required:
  --source <path>       Directory containing plugin(s) in Moodle layout
                        (e.g., with mod/, blocks/ subdirectories)

Environment (auto-detected if not provided):
  --orb <name>          Orb VM name
  --container <name>    Docker container name/ID
  --webroot <path>      Moodle webroot path inside the container

Behavior:
  --dry-run             Show what would happen, don't change anything
  --skip-upgrade        Copy files but don't run admin/cli/upgrade.php
  --skip-cache          Don't purge caches after deployment
  --phpunit-init        Run admin/tool/phpunit/cli/init.php after deploy
  --verbose             Detailed output
  --no-config           Don't read or save ~/.moodle-deploy.conf
  --help                Show this help

Examples:
  # Auto-detect everything, deploy plugin
  deploy.sh --source ./my-plugin

  # Dry run first
  deploy.sh --source ./my-plugin --dry-run

  # Deploy + prepare PHPUnit test DB
  deploy.sh --source ./my-plugin --phpunit-init

  # Explicit environment (skip detection)
  deploy.sh --source ./my-plugin --orb default --container moodle-app-1 --webroot /bitnami/moodle
EOF
    exit 0
}

NO_CONFIG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)       SOURCE_DIR="$2"; shift 2 ;;
        --orb)          ORB_VM="$2"; shift 2 ;;
        --container)    CONTAINER="$2"; shift 2 ;;
        --webroot)      WEBROOT="$2"; shift 2 ;;
        --dry-run)      DRY_RUN=true; shift ;;
        --skip-upgrade) SKIP_UPGRADE=true; shift ;;
        --skip-cache)   SKIP_CACHE=true; shift ;;
        --phpunit-init) PHPUNIT_INIT=true; shift ;;
        --verbose)      VERBOSE=true; shift ;;
        --no-config)    NO_CONFIG=true; shift ;;
        --help|-h)      show_help ;;
        *) die "Unknown option: $1. Use --help for usage." ;;
    esac
done

[[ -z "$SOURCE_DIR" ]] && die "Missing --source. Use --help for usage."
[[ ! -d "$SOURCE_DIR" ]] && die "Source directory does not exist: $SOURCE_DIR"

# ---------- Load saved config ----------
load_config() {
    if [[ "$NO_CONFIG" == true ]] || [[ ! -f "$CONFIG_FILE" ]]; then
        return
    fi
    debug "Loading saved config from $CONFIG_FILE"
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
    # Only use saved values if not explicitly provided
    [[ -z "$ORB_VM" ]] && ORB_VM="${SAVED_ORB_VM:-}"
    [[ -z "$CONTAINER" ]] && CONTAINER="${SAVED_CONTAINER:-}"
    [[ -z "$WEBROOT" ]] && WEBROOT="${SAVED_WEBROOT:-}"
}

save_config() {
    if [[ "$NO_CONFIG" == true ]] || [[ "$DRY_RUN" == true ]]; then
        return
    fi
    cat > "$CONFIG_FILE" <<EOF
# Auto-generated by moodle-deploy on $(date -Iseconds)
SAVED_ORB_VM="$ORB_VM"
SAVED_CONTAINER="$CONTAINER"
SAVED_WEBROOT="$WEBROOT"
EOF
    debug "Saved config to $CONFIG_FILE"
}

# ---------- Step 1: Find Orb VM ----------
detect_orb_vm() {
    step "Detecting Orb VM"

    if [[ -n "$ORB_VM" ]]; then
        info "Using provided VM: $ORB_VM"
        return
    fi

    if ! command -v orb &>/dev/null; then
        die "orb command not found. Is Orb installed?"
    fi

    # Get list of running VMs
    local vms
    vms=$(orb list 2>/dev/null | grep -i "running" | awk '{print $1}' || true)

    if [[ -z "$vms" ]]; then
        die "No running Orb VMs found. Start your VM first (orb start <name>)."
    fi

    local count
    count=$(echo "$vms" | wc -l | tr -d ' ')

    if [[ "$count" -eq 1 ]]; then
        ORB_VM=$(echo "$vms" | head -1)
        success "Found Orb VM: $ORB_VM"
    else
        warn "Multiple running VMs found:"
        echo "$vms" | while read -r vm; do echo "  - $vm"; done
        # Use the first one
        ORB_VM=$(echo "$vms" | head -1)
        warn "Using first VM: $ORB_VM (override with --orb <name>)"
    fi
}

# Helper: run a command inside the Orb VM
orb_exec() {
    orb -m "$ORB_VM" "$@"
}

# ---------- Step 2: Find Docker container ----------
detect_container() {
    step "Detecting Moodle Docker container"

    if [[ -n "$CONTAINER" ]]; then
        info "Using provided container: $CONTAINER"
        return
    fi

    # List running containers, look for moodle-related ones
    local containers
    containers=$(orb_exec docker ps --format '{{.Names}}\t{{.Image}}' 2>/dev/null || true)

    if [[ -z "$containers" ]]; then
        die "No running Docker containers found in VM '$ORB_VM'. Is Docker running? Try: orb -m $ORB_VM docker compose up -d"
    fi

    debug "Running containers:"
    $VERBOSE && echo "$containers" | sed 's/^/    /' || true

    # Try to find a Moodle container by image name or container name
    local moodle_containers=""

    while IFS=$'\t' read -r name image; do
        if echo "$name $image" | grep -qi "moodle"; then
            moodle_containers="${moodle_containers}${name}\n"
        fi
    done <<< "$containers"

    moodle_containers=$(echo -e "$moodle_containers" | sed '/^$/d')

    if [[ -z "$moodle_containers" ]]; then
        # Fallback: look for PHP/Apache/Nginx containers that might be Moodle
        warn "No container with 'moodle' in name/image found."
        warn "Available containers:"
        echo "$containers" | while IFS=$'\t' read -r name image; do
            echo "    $name ($image)"
        done
        die "Specify the container with --container <name>"
    fi

    local count
    count=$(echo "$moodle_containers" | wc -l | tr -d ' ')

    if [[ "$count" -eq 1 ]]; then
        CONTAINER=$(echo "$moodle_containers" | head -1)
        success "Found Moodle container: $CONTAINER"
    else
        warn "Multiple Moodle-related containers found:"
        echo "$moodle_containers" | while read -r c; do echo "  - $c"; done
        # Pick the one most likely to be the app (not db/cache)
        CONTAINER=$(echo "$moodle_containers" | grep -vi -e "db" -e "postgres" -e "mysql" -e "mariadb" -e "redis" -e "memcache" | head -1 || echo "$moodle_containers" | head -1)
        warn "Using: $CONTAINER (override with --container <name>)"
    fi
}

# Helper: run a command inside the Docker container (via Orb)
docker_exec() {
    orb_exec docker exec "$CONTAINER" "$@"
}

# ---------- Step 3: Find Moodle webroot ----------
detect_webroot() {
    step "Detecting Moodle webroot"

    if [[ -n "$WEBROOT" ]]; then
        info "Using provided webroot: $WEBROOT"
        return
    fi

    # Check common Moodle paths inside the container
    local candidates=(
        "/bitnami/moodle"
        "/var/www/html"
        "/var/www/html/moodle"
        "/var/www/moodle"
        "/opt/moodle"
        "/app/moodle"
    )

    for path in "${candidates[@]}"; do
        if docker_exec test -f "$path/config.php" 2>/dev/null; then
            WEBROOT="$path"
            success "Found Moodle webroot: $WEBROOT"
            return
        fi
    done

    # Last resort: find config.php
    local found
    found=$(docker_exec find / -maxdepth 4 -name "config.php" -path "*/moodle/*" -o -name "config.php" -path "*/html/*" 2>/dev/null | head -1 || true)

    if [[ -n "$found" ]]; then
        WEBROOT=$(dirname "$found")
        success "Found Moodle webroot (via search): $WEBROOT"
        return
    fi

    die "Could not find Moodle webroot. Specify it with --webroot <path>"
}

# ---------- Step 4: Discover plugins to deploy ----------
discover_plugins() {
    step "Discovering plugins in source directory"

    PLUGINS=()

    # Look for standard Moodle plugin directories
    local plugin_types=("mod" "blocks" "local" "theme" "auth" "enrol" "report"
                        "filter" "format" "question" "admin" "availability"
                        "plagiarism" "repository" "tool" "grade")

    for ptype in "${plugin_types[@]}"; do
        if [[ -d "$SOURCE_DIR/$ptype" ]]; then
            for plugin_dir in "$SOURCE_DIR/$ptype"/*/; do
                if [[ -d "$plugin_dir" ]]; then
                    local plugin_name
                    plugin_name=$(basename "$plugin_dir")
                    # Verify it looks like a Moodle plugin (has version.php)
                    if [[ -f "$plugin_dir/version.php" ]]; then
                        PLUGINS+=("$ptype/$plugin_name")
                        success "Found: $ptype/$plugin_name"
                    else
                        warn "Skipping $ptype/$plugin_name (no version.php)"
                    fi
                fi
            done
        fi
    done

    # Also check if the source dir itself is a plugin
    if [[ ${#PLUGINS[@]} -eq 0 ]] && [[ -f "$SOURCE_DIR/version.php" ]]; then
        # Try to determine plugin type from version.php
        local component
        component=$(grep -oP "\\\$plugin->component\s*=\s*'([^']+)'" "$SOURCE_DIR/version.php" | grep -oP "'[^']+'" | tr -d "'" || true)
        if [[ -n "$component" ]]; then
            local ptype pname
            ptype=$(echo "$component" | cut -d_ -f1)
            pname=$(echo "$component" | cut -d_ -f2-)
            # Map component prefix to directory
            case "$ptype" in
                mod)    PLUGINS+=("mod/$pname") ;;
                block)  PLUGINS+=("blocks/$pname") ;;
                local)  PLUGINS+=("local/$pname") ;;
                *)      PLUGINS+=("$ptype/$pname") ;;
            esac
            success "Found standalone plugin: ${PLUGINS[-1]}"
        fi
    fi

    if [[ ${#PLUGINS[@]} -eq 0 ]]; then
        die "No Moodle plugins found in $SOURCE_DIR. Expected directories like mod/<name>/, blocks/<name>/, etc."
    fi

    info "Total plugins to deploy: ${#PLUGINS[@]}"
}

# ---------- Step 5: Copy files ----------
deploy_plugins() {
    step "Deploying plugins"

    for plugin in "${PLUGINS[@]}"; do
        local src_path="$SOURCE_DIR/$plugin"
        local dest_path="$WEBROOT/$plugin"

        info "Deploying $plugin → $dest_path"

        if [[ "$DRY_RUN" == true ]]; then
            info "[DRY RUN] Would copy $src_path → container:$dest_path"
            # Show file count
            local file_count
            file_count=$(find "$src_path" -type f | wc -l | tr -d ' ')
            debug "  $file_count files to copy"
            continue
        fi

        # Remove old version inside container (clean deploy)
        debug "Removing old version: $dest_path"
        docker_exec rm -rf "$dest_path" 2>/dev/null || true

        # Ensure parent directory exists
        local parent_dir
        parent_dir=$(dirname "$dest_path")
        docker_exec mkdir -p "$parent_dir" 2>/dev/null || true

        # Copy files into the container via Orb
        # We need to use a temp tar because docker cp goes through Orb
        local tmp_tar="/tmp/moodle-deploy-$$.tar"
        debug "Creating archive..."
        (cd "$SOURCE_DIR" && tar cf "$tmp_tar" "$plugin")

        debug "Copying to Orb VM..."
        orb_exec docker cp "$tmp_tar" "$CONTAINER:/tmp/moodle-deploy.tar"

        debug "Extracting in container..."
        docker_exec tar xf /tmp/moodle-deploy.tar -C "$WEBROOT/"
        docker_exec rm -f /tmp/moodle-deploy.tar

        rm -f "$tmp_tar"

        # Fix permissions (common issue with Docker Moodle setups)
        debug "Fixing permissions..."
        docker_exec chown -R www-data:www-data "$dest_path" 2>/dev/null || \
        docker_exec chown -R daemon:daemon "$dest_path" 2>/dev/null || \
        docker_exec chmod -R 755 "$dest_path" 2>/dev/null || true

        success "Deployed: $plugin"
    done
}

# ---------- Step 6: Run Moodle CLI ----------
run_upgrade() {
    if [[ "$SKIP_UPGRADE" == true ]]; then
        info "Skipping upgrade (--skip-upgrade)"
        return
    fi

    step "Running Moodle upgrade"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/cli/upgrade.php --non-interactive"
        return
    fi

    # Determine the PHP user (varies by Docker image)
    local php_user="www-data"
    if docker_exec id daemon &>/dev/null; then
        # Bitnami images use 'daemon'
        if docker_exec test -d /bitnami 2>/dev/null; then
            php_user="daemon"
        fi
    fi

    info "Running upgrade as $php_user..."
    local output
    if output=$(orb_exec docker exec -u "$php_user" "$CONTAINER" \
        php "$WEBROOT/admin/cli/upgrade.php" --non-interactive 2>&1); then
        success "Upgrade completed successfully"
        $VERBOSE && echo "$output" | tail -20 | sed 's/^/    /' || true
    else
        local exit_code=$?
        warn "Upgrade exited with code $exit_code"
        echo "$output" | tail -30 | sed 's/^/    /'
        # Don't die — some exit codes are benign (e.g., "nothing to upgrade")
        if echo "$output" | grep -qi "error\|fatal\|exception"; then
            error "Upgrade had errors — check the output above"
        else
            info "This is likely OK (nothing new to upgrade)"
        fi
    fi
}

purge_caches() {
    if [[ "$SKIP_CACHE" == true ]]; then
        info "Skipping cache purge (--skip-cache)"
        return
    fi

    step "Purging Moodle caches"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/cli/purge_caches.php"
        return
    fi

    local php_user="www-data"
    if docker_exec test -d /bitnami 2>/dev/null; then
        php_user="daemon"
    fi

    if docker_exec php "$WEBROOT/admin/cli/purge_caches.php" 2>&1; then
        success "Caches purged"
    else
        warn "Cache purge had issues (may be non-critical)"
    fi
}

run_phpunit_init() {
    if [[ "$PHPUNIT_INIT" != true ]]; then
        return
    fi

    step "Initializing PHPUnit test environment"

    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY RUN] Would run: php admin/tool/phpunit/cli/init.php"
        return
    fi

    info "This may take a minute..."
    if docker_exec php "$WEBROOT/admin/tool/phpunit/cli/init.php" 2>&1; then
        success "PHPUnit initialized"
    else
        warn "PHPUnit init had issues — check if phpunit is configured in config.php"
    fi
}

# ---------- Main ----------
main() {
    echo -e "\n${BOLD}🚀 Moodle Deploy${NC}"
    echo -e "───────────────────────────────────\n"

    if [[ "$DRY_RUN" == true ]]; then
        warn "DRY RUN MODE — no changes will be made\n"
    fi

    load_config
    detect_orb_vm
    detect_container
    detect_webroot
    discover_plugins

    echo ""
    info "Environment summary:"
    echo -e "    Orb VM:     ${BOLD}$ORB_VM${NC}"
    echo -e "    Container:  ${BOLD}$CONTAINER${NC}"
    echo -e "    Webroot:    ${BOLD}$WEBROOT${NC}"
    echo -e "    Plugins:    ${BOLD}${PLUGINS[*]}${NC}"
    echo ""

    deploy_plugins
    run_upgrade
    purge_caches
    run_phpunit_init

    # Save config for next time
    save_config

    echo ""
    if [[ "$DRY_RUN" == true ]]; then
        success "${BOLD}Dry run complete.${NC} Rerun without --dry-run to deploy."
    else
        success "${BOLD}Deployment complete!${NC}"
        info "Open your Moodle in the browser to verify."
        info "Config saved to $CONFIG_FILE for faster future deploys."
    fi
}

main
